services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress      
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','https://monkey-space-couscous-5wg4569q5qqf4vqp-8080.app.github.dev');
        define('WP_SITEURL','https://monkey-space-couscous-5wg4569q5qqf4vqp-8080.app.github.dev');
      # 真實環境要加
      # $_SERVER['HTTPS'] = 'on';  
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  wordpress:
  db: